### PR TITLE
Fix/dependencies refs

### PR DESCRIPTION
**Pull request by dzdidi**
# fix dependency usage

### CODE REVIEW

**Review by dylanseago — DISMISSED** [review]

**Comment by dzdidi** [comment]
@caleb-bitaccess may you please also confirm that this correct and intended usage? Otherwise I might just scrap it

**Review by caleb-bitaccess — COMMENTED** [review]
The bip32 lib did not change much. just the way we import. As long as the coinlib-bitcoin-cash is still using bitcoinjs#cash520 it should be fine.
Besides, the coinlib probably already had 2 versions of bip32, one from coinlib-common, and one from bitcoinjs#cash520

**Comment by dzdidi** [comment]
@dylanseago @caleb-bitaccess install from root resolved the issue, thank you for suggestion. Also I've noticed that it does not affect `packages/**/package-lock.json` files and installs all the packages' dependencies into root's `node_modules`. I wonder if it will make sense to remove `packages/**/package-lock.json` ?

**Comment by dzdidi** [comment]
All tests are passing:
```
Test Suites: 1 skipped, 62 passed, 62 of 63 total
Tests:       32 skipped, 1444 passed, 1476 total
Snapshots:   0 total
Time:        118.288 s
Ran all test suites in 10 projects.
```

**Review by dylanseago — APPROVED** [review]

**Pull request merged**
